/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { BackupResponseDto } from '../model/backupResponse.dto';
import { HealthCheckDto } from '../model/healthCheck.dto';
import { InfoDto } from '../model/info.dto';
import { MessageDto } from '../model/message.dto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class DefaultApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Backup
     * Trigger a database backup. Only applicable for SQLite databases.
     * @param {*} [backupBackupPostOpts.config] Override http request option.
     */
    public backupBackupPost(backupBackupPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<BackupResponseDto>>;
    public backupBackupPost(backupBackupPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<BackupResponseDto>(`${this.basePath}/backup`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...backupBackupPostOpts?.config,
                        headers: {...headers, ...backupBackupPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Health
     * Return a health check.
     * @param {*} [healthHealthGetOpts.config] Override http request option.
     */
    public healthHealthGet(healthHealthGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<HealthCheckDto>>;
    public healthHealthGet(healthHealthGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<HealthCheckDto>(`${this.basePath}/health`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...healthHealthGetOpts?.config,
                        headers: {...headers, ...healthHealthGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Info
     * Return general info about the API.
     * @param {*} [infoInfoGetOpts.config] Override http request option.
     */
    public infoInfoGet(infoInfoGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<InfoDto>>;
    public infoInfoGet(infoInfoGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<InfoDto>(`${this.basePath}/info`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...infoInfoGetOpts?.config,
                        headers: {...headers, ...infoInfoGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
