/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ExportFormatDto } from '../model/exportFormat.dto';
import { HTTPValidationErrorDto } from '../model/hTTPValidationError.dto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for exportFilamentsExportFilamentsGet operation in ExportApi.
 * @export
 * @interface ExportApiExportFilamentsExportFilamentsGetRequest
 */
export interface ExportApiExportFilamentsExportFilamentsGetRequest {
    /**
     * 
     * @type {ExportFormatDto}
     * @memberof ExportApiExportFilamentsExportFilamentsGet
     */
    readonly fmt: ExportFormatDto
}

/**
 * Request parameters for exportSpoolsExportSpoolsGet operation in ExportApi.
 * @export
 * @interface ExportApiExportSpoolsExportSpoolsGetRequest
 */
export interface ExportApiExportSpoolsExportSpoolsGetRequest {
    /**
     * 
     * @type {ExportFormatDto}
     * @memberof ExportApiExportSpoolsExportSpoolsGet
     */
    readonly fmt: ExportFormatDto
}

/**
 * Request parameters for exportVendorsExportVendorsGet operation in ExportApi.
 * @export
 * @interface ExportApiExportVendorsExportVendorsGetRequest
 */
export interface ExportApiExportVendorsExportVendorsGetRequest {
    /**
     * 
     * @type {ExportFormatDto}
     * @memberof ExportApiExportVendorsExportVendorsGet
     */
    readonly fmt: ExportFormatDto
}


@Injectable()
export class ExportApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Export Filaments
     * Export the list of filaments in various formats. Vendor data is included.
     * @param {ExportApiExportFilamentsExportFilamentsGetRequest} requestParameters Request parameters.
     * @param {*} [exportFilamentsExportFilamentsGetOpts.config] Override http request option.
     */
    public exportFilamentsExportFilamentsGet(requestParameters: ExportApiExportFilamentsExportFilamentsGetRequest, exportFilamentsExportFilamentsGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public exportFilamentsExportFilamentsGet(requestParameters: ExportApiExportFilamentsExportFilamentsGetRequest, exportFilamentsExportFilamentsGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            fmt,
        } = requestParameters;

        if (fmt === null || fmt === undefined) {
            throw new Error('Required parameter fmt was null or undefined when calling exportFilamentsExportFilamentsGet.');
        }

        let queryParameters = new URLSearchParams();
        if (fmt !== undefined && fmt !== null) {
            queryParameters.append('fmt', <any>fmt);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/export/filaments`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...exportFilamentsExportFilamentsGetOpts?.config,
                        headers: {...headers, ...exportFilamentsExportFilamentsGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Export Spools
     * Export the list of spools in various formats. Filament and vendor data is included.
     * @param {ExportApiExportSpoolsExportSpoolsGetRequest} requestParameters Request parameters.
     * @param {*} [exportSpoolsExportSpoolsGetOpts.config] Override http request option.
     */
    public exportSpoolsExportSpoolsGet(requestParameters: ExportApiExportSpoolsExportSpoolsGetRequest, exportSpoolsExportSpoolsGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public exportSpoolsExportSpoolsGet(requestParameters: ExportApiExportSpoolsExportSpoolsGetRequest, exportSpoolsExportSpoolsGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            fmt,
        } = requestParameters;

        if (fmt === null || fmt === undefined) {
            throw new Error('Required parameter fmt was null or undefined when calling exportSpoolsExportSpoolsGet.');
        }

        let queryParameters = new URLSearchParams();
        if (fmt !== undefined && fmt !== null) {
            queryParameters.append('fmt', <any>fmt);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/export/spools`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...exportSpoolsExportSpoolsGetOpts?.config,
                        headers: {...headers, ...exportSpoolsExportSpoolsGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Export Vendors
     * Export the list of vendors in various formats.
     * @param {ExportApiExportVendorsExportVendorsGetRequest} requestParameters Request parameters.
     * @param {*} [exportVendorsExportVendorsGetOpts.config] Override http request option.
     */
    public exportVendorsExportVendorsGet(requestParameters: ExportApiExportVendorsExportVendorsGetRequest, exportVendorsExportVendorsGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public exportVendorsExportVendorsGet(requestParameters: ExportApiExportVendorsExportVendorsGetRequest, exportVendorsExportVendorsGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            fmt,
        } = requestParameters;

        if (fmt === null || fmt === undefined) {
            throw new Error('Required parameter fmt was null or undefined when calling exportVendorsExportVendorsGet.');
        }

        let queryParameters = new URLSearchParams();
        if (fmt !== undefined && fmt !== null) {
            queryParameters.append('fmt', <any>fmt);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/export/vendors`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...exportVendorsExportVendorsGetOpts?.config,
                        headers: {...headers, ...exportVendorsExportVendorsGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
