/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ExternalFilamentDto } from '../model/externalFilament.dto';
import { ExternalMaterialDto } from '../model/externalMaterial.dto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class ExternalApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Get All External Filaments
     * Get all external filaments.
     * @param {*} [getAllExternalFilamentsExternalFilamentGetOpts.config] Override http request option.
     */
    public getAllExternalFilamentsExternalFilamentGet(getAllExternalFilamentsExternalFilamentGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<ExternalFilamentDto>>>;
    public getAllExternalFilamentsExternalFilamentGet(getAllExternalFilamentsExternalFilamentGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<ExternalFilamentDto>>(`${this.basePath}/external/filament`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...getAllExternalFilamentsExternalFilamentGetOpts?.config,
                        headers: {...headers, ...getAllExternalFilamentsExternalFilamentGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Get All External Materials
     * Get all external materials.
     * @param {*} [getAllExternalMaterialsExternalMaterialGetOpts.config] Override http request option.
     */
    public getAllExternalMaterialsExternalMaterialGet(getAllExternalMaterialsExternalMaterialGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<ExternalMaterialDto>>>;
    public getAllExternalMaterialsExternalMaterialGet(getAllExternalMaterialsExternalMaterialGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<ExternalMaterialDto>>(`${this.basePath}/external/material`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...getAllExternalMaterialsExternalMaterialGetOpts?.config,
                        headers: {...headers, ...getAllExternalMaterialsExternalMaterialGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
