/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { HTTPValidationErrorDto } from '../model/hTTPValidationError.dto';
import { RenameLocationBodyDto } from '../model/renameLocationBody.dto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for renameLocationLocationLocationPatch operation in OtherApi.
 * @export
 * @interface OtherApiRenameLocationLocationLocationPatchRequest
 */
export interface OtherApiRenameLocationLocationLocationPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof OtherApiRenameLocationLocationLocationPatch
     */
    readonly location: string

    /**
     * 
     * @type {RenameLocationBodyDto}
     * @memberof OtherApiRenameLocationLocationLocationPatch
     */
    readonly 'RenameLocationBodyDto': RenameLocationBodyDto
}


@Injectable()
export class OtherApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Find Article Numbers
     * Get a list of all article numbers.
     * @param {*} [findArticleNumbersArticleNumberGetOpts.config] Override http request option.
     */
    public findArticleNumbersArticleNumberGet(findArticleNumbersArticleNumberGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<string | null>>>;
    public findArticleNumbersArticleNumberGet(findArticleNumbersArticleNumberGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<string | null>>(`${this.basePath}/article-number`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...findArticleNumbersArticleNumberGetOpts?.config,
                        headers: {...headers, ...findArticleNumbersArticleNumberGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Find Locations
     * Get a list of all spool locations.
     * @param {*} [findLocationsLocationGetOpts.config] Override http request option.
     */
    public findLocationsLocationGet(findLocationsLocationGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<string | null>>>;
    public findLocationsLocationGet(findLocationsLocationGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<string | null>>(`${this.basePath}/location`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...findLocationsLocationGetOpts?.config,
                        headers: {...headers, ...findLocationsLocationGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Find Lot Numbers
     * Get a list of all lot numbers.
     * @param {*} [findLotNumbersLotNumberGetOpts.config] Override http request option.
     */
    public findLotNumbersLotNumberGet(findLotNumbersLotNumberGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<string | null>>>;
    public findLotNumbersLotNumberGet(findLotNumbersLotNumberGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<string | null>>(`${this.basePath}/lot-number`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...findLotNumbersLotNumberGetOpts?.config,
                        headers: {...headers, ...findLotNumbersLotNumberGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Find Materials
     * Get a list of all filament materials.
     * @param {*} [findMaterialsMaterialGetOpts.config] Override http request option.
     */
    public findMaterialsMaterialGet(findMaterialsMaterialGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<string | null>>>;
    public findMaterialsMaterialGet(findMaterialsMaterialGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<string | null>>(`${this.basePath}/material`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...findMaterialsMaterialGetOpts?.config,
                        headers: {...headers, ...findMaterialsMaterialGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Rename Location
     * Rename a spool location. All spools in this location will be moved to the new location.
     * @param {OtherApiRenameLocationLocationLocationPatchRequest} requestParameters Request parameters.
     * @param {*} [renameLocationLocationLocationPatchOpts.config] Override http request option.
     */
    public renameLocationLocationLocationPatch(requestParameters: OtherApiRenameLocationLocationLocationPatchRequest, renameLocationLocationLocationPatchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<string>>;
    public renameLocationLocationLocationPatch(requestParameters: OtherApiRenameLocationLocationLocationPatchRequest, renameLocationLocationLocationPatchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            location,
            'RenameLocationBodyDto': renameLocationBodyDto,
        } = requestParameters;

        if (location === null || location === undefined) {
            throw new Error('Required parameter location was null or undefined when calling renameLocationLocationLocationPatch.');
        }

        if (renameLocationBodyDto === null || renameLocationBodyDto === undefined) {
            throw new Error('Required parameter renameLocationBodyDto was null or undefined when calling renameLocationLocationLocationPatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<string>(`${this.basePath}/location/${encodeURIComponent(String(location))}`,
                    renameLocationBodyDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...renameLocationLocationLocationPatchOpts?.config,
                        headers: {...headers, ...renameLocationLocationLocationPatchOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
