/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { HTTPValidationErrorDto } from '../model/hTTPValidationError.dto';
import { MessageDto } from '../model/message.dto';
import { SpoolDto } from '../model/spool.dto';
import { SpoolEventDto } from '../model/spoolEvent.dto';
import { SpoolMeasureParametersDto } from '../model/spoolMeasureParameters.dto';
import { SpoolParametersDto } from '../model/spoolParameters.dto';
import { SpoolUpdateParametersDto } from '../model/spoolUpdateParameters.dto';
import { SpoolUseParametersDto } from '../model/spoolUseParameters.dto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for addSpoolSpoolPost operation in SpoolApi.
 * @export
 * @interface SpoolApiAddSpoolSpoolPostRequest
 */
export interface SpoolApiAddSpoolSpoolPostRequest {
    /**
     * 
     * @type {SpoolParametersDto}
     * @memberof SpoolApiAddSpoolSpoolPost
     */
    readonly 'SpoolParametersDto': SpoolParametersDto
}

/**
 * Request parameters for deleteSpoolSpoolSpoolIdDelete operation in SpoolApi.
 * @export
 * @interface SpoolApiDeleteSpoolSpoolSpoolIdDeleteRequest
 */
export interface SpoolApiDeleteSpoolSpoolSpoolIdDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof SpoolApiDeleteSpoolSpoolSpoolIdDelete
     */
    readonly 'spool_id': number
}

/**
 * Request parameters for findSpoolSpoolGet operation in SpoolApi.
 * @export
 * @interface SpoolApiFindSpoolSpoolGetRequest
 */
export interface SpoolApiFindSpoolSpoolGetRequest {
    /**
     * See filament.name.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament_name'?: string

    /**
     * See filament.id.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament_id'?: string

    /**
     * See filament.material.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament_material'?: string

    /**
     * See filament.vendor.name.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'vendor_name'?: string

    /**
     * See filament.vendor.id.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'vendor_id'?: string

    /**
     * Partial case-insensitive search term for the filament name. Separate multiple terms with a comma. Specify an empty string to match spools with no filament name. Surround a term with quotes to search for the exact term.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament.name'?: string

    /**
     * Match an exact filament ID. Separate multiple IDs with a comma.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament.id'?: string

    /**
     * Partial case-insensitive search term for the filament material. Separate multiple terms with a comma. Specify an empty string to match spools with no filament material. Surround a term with quotes to search for the exact term.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament.material'?: string

    /**
     * Partial case-insensitive search term for the filament vendor name. Separate multiple terms with a comma. Specify an empty string to match spools with no vendor name. Surround a term with quotes to search for the exact term.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament.vendor.name'?: string

    /**
     * Match an exact vendor ID. Separate multiple IDs with a comma. Set it to -1 to match spools with filaments with no vendor.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'filament.vendor.id'?: string

    /**
     * Partial case-insensitive search term for the spool location. Separate multiple terms with a comma. Specify an empty string to match spools with no location. Surround a term with quotes to search for the exact term.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly location?: string

    /**
     * Partial case-insensitive search term for the spool lot number. Separate multiple terms with a comma. Specify an empty string to match spools with no lot nr. Surround a term with quotes to search for the exact term.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'lot_nr'?: string

    /**
     * Whether to include archived spools in the search results.
     * @type {boolean}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly 'allow_archived'?: boolean

    /**
     * Sort the results by the given field. Should be a comma-separate string with \&quot;field:direction\&quot; items.
     * @type {string}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly sort?: string

    /**
     * Maximum number of items in the response.
     * @type {number}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly limit?: number

    /**
     * Offset in the full result set if a limit is set.
     * @type {number}
     * @memberof SpoolApiFindSpoolSpoolGet
     */
    readonly offset?: number
}

/**
 * Request parameters for getSpoolSpoolSpoolIdGet operation in SpoolApi.
 * @export
 * @interface SpoolApiGetSpoolSpoolSpoolIdGetRequest
 */
export interface SpoolApiGetSpoolSpoolSpoolIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof SpoolApiGetSpoolSpoolSpoolIdGet
     */
    readonly 'spool_id': number
}

/**
 * Request parameters for updateSpoolSpoolSpoolIdPatch operation in SpoolApi.
 * @export
 * @interface SpoolApiUpdateSpoolSpoolSpoolIdPatchRequest
 */
export interface SpoolApiUpdateSpoolSpoolSpoolIdPatchRequest {
    /**
     * 
     * @type {number}
     * @memberof SpoolApiUpdateSpoolSpoolSpoolIdPatch
     */
    readonly 'spool_id': number

    /**
     * 
     * @type {SpoolUpdateParametersDto}
     * @memberof SpoolApiUpdateSpoolSpoolSpoolIdPatch
     */
    readonly 'SpoolUpdateParametersDto': SpoolUpdateParametersDto
}

/**
 * Request parameters for useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut operation in SpoolApi.
 * @export
 * @interface SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutRequest
 */
export interface SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutRequest {
    /**
     * 
     * @type {number}
     * @memberof SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut
     */
    readonly 'spool_id': number

    /**
     * 
     * @type {SpoolMeasureParametersDto}
     * @memberof SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut
     */
    readonly 'SpoolMeasureParametersDto': SpoolMeasureParametersDto
}

/**
 * Request parameters for useSpoolFilamentSpoolSpoolIdUsePut operation in SpoolApi.
 * @export
 * @interface SpoolApiUseSpoolFilamentSpoolSpoolIdUsePutRequest
 */
export interface SpoolApiUseSpoolFilamentSpoolSpoolIdUsePutRequest {
    /**
     * 
     * @type {number}
     * @memberof SpoolApiUseSpoolFilamentSpoolSpoolIdUsePut
     */
    readonly 'spool_id': number

    /**
     * 
     * @type {SpoolUseParametersDto}
     * @memberof SpoolApiUseSpoolFilamentSpoolSpoolIdUsePut
     */
    readonly 'SpoolUseParametersDto': SpoolUseParametersDto
}


@Injectable()
export class SpoolApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Add Spool
     * Add a new spool to the database. Only specify either remaining_weight or used_weight. If no weight is set, the spool will be assumed to be full.
     * @param {SpoolApiAddSpoolSpoolPostRequest} requestParameters Request parameters.
     * @param {*} [addSpoolSpoolPostOpts.config] Override http request option.
     */
    public addSpoolSpoolPost(requestParameters: SpoolApiAddSpoolSpoolPostRequest, addSpoolSpoolPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SpoolDto>>;
    public addSpoolSpoolPost(requestParameters: SpoolApiAddSpoolSpoolPostRequest, addSpoolSpoolPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'SpoolParametersDto': spoolParametersDto,
        } = requestParameters;

        if (spoolParametersDto === null || spoolParametersDto === undefined) {
            throw new Error('Required parameter spoolParametersDto was null or undefined when calling addSpoolSpoolPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<SpoolDto>(`${this.basePath}/spool`,
                    spoolParametersDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...addSpoolSpoolPostOpts?.config,
                        headers: {...headers, ...addSpoolSpoolPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Delete Spool
     * Delete a spool.
     * @param {SpoolApiDeleteSpoolSpoolSpoolIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [deleteSpoolSpoolSpoolIdDeleteOpts.config] Override http request option.
     */
    public deleteSpoolSpoolSpoolIdDelete(requestParameters: SpoolApiDeleteSpoolSpoolSpoolIdDeleteRequest, deleteSpoolSpoolSpoolIdDeleteOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<MessageDto>>;
    public deleteSpoolSpoolSpoolIdDelete(requestParameters: SpoolApiDeleteSpoolSpoolSpoolIdDeleteRequest, deleteSpoolSpoolSpoolIdDeleteOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'spool_id': spoolId,
        } = requestParameters;

        if (spoolId === null || spoolId === undefined) {
            throw new Error('Required parameter spoolId was null or undefined when calling deleteSpoolSpoolSpoolIdDelete.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<MessageDto>(`${this.basePath}/spool/${encodeURIComponent(String(spoolId))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...deleteSpoolSpoolSpoolIdDeleteOpts?.config,
                        headers: {...headers, ...deleteSpoolSpoolSpoolIdDeleteOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Find Spool
     * Get a list of spools that matches the search query. A websocket is served on the same path to listen for updates to any spool, or added or deleted spools. See the HTTP Response code 299 for the content of the websocket messages.
     * @param {SpoolApiFindSpoolSpoolGetRequest} requestParameters Request parameters.
     * @param {*} [findSpoolSpoolGetOpts.config] Override http request option.
     */
    public findSpoolSpoolGet(requestParameters: SpoolApiFindSpoolSpoolGetRequest, findSpoolSpoolGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<SpoolDto>>>;
    public findSpoolSpoolGet(requestParameters: SpoolApiFindSpoolSpoolGetRequest, findSpoolSpoolGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'filament_name': filamentName,
            'filament_id': filamentId,
            'filament_material': filamentMaterial,
            'vendor_name': vendorName,
            'vendor_id': vendorId,
            'filament.name': filamentName2,
            'filament.id': filamentId2,
            'filament.material': filamentMaterial2,
            'filament.vendor.name': filamentVendorName,
            'filament.vendor.id': filamentVendorId,
            location,
            'lot_nr': lotNr,
            'allow_archived': allowArchived,
            sort,
            limit,
            offset,
        } = requestParameters;

        let queryParameters = new URLSearchParams();
        if (filamentName !== undefined && filamentName !== null) {
            queryParameters.append('filament_name', <any>filamentName);
        }
        if (filamentId !== undefined && filamentId !== null) {
            queryParameters.append('filament_id', <any>filamentId);
        }
        if (filamentMaterial !== undefined && filamentMaterial !== null) {
            queryParameters.append('filament_material', <any>filamentMaterial);
        }
        if (vendorName !== undefined && vendorName !== null) {
            queryParameters.append('vendor_name', <any>vendorName);
        }
        if (vendorId !== undefined && vendorId !== null) {
            queryParameters.append('vendor_id', <any>vendorId);
        }
        if (filamentName2 !== undefined && filamentName2 !== null) {
            queryParameters.append('filament.name', <any>filamentName2);
        }
        if (filamentId2 !== undefined && filamentId2 !== null) {
            queryParameters.append('filament.id', <any>filamentId2);
        }
        if (filamentMaterial2 !== undefined && filamentMaterial2 !== null) {
            queryParameters.append('filament.material', <any>filamentMaterial2);
        }
        if (filamentVendorName !== undefined && filamentVendorName !== null) {
            queryParameters.append('filament.vendor.name', <any>filamentVendorName);
        }
        if (filamentVendorId !== undefined && filamentVendorId !== null) {
            queryParameters.append('filament.vendor.id', <any>filamentVendorId);
        }
        if (location !== undefined && location !== null) {
            queryParameters.append('location', <any>location);
        }
        if (lotNr !== undefined && lotNr !== null) {
            queryParameters.append('lot_nr', <any>lotNr);
        }
        if (allowArchived !== undefined && allowArchived !== null) {
            queryParameters.append('allow_archived', <any>allowArchived);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters.append('offset', <any>offset);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<SpoolDto>>(`${this.basePath}/spool`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...findSpoolSpoolGetOpts?.config,
                        headers: {...headers, ...findSpoolSpoolGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Get Spool
     * Get a specific spool. A websocket is served on the same path to listen for changes to the spool. See the HTTP Response code 299 for the content of the websocket messages.
     * @param {SpoolApiGetSpoolSpoolSpoolIdGetRequest} requestParameters Request parameters.
     * @param {*} [getSpoolSpoolSpoolIdGetOpts.config] Override http request option.
     */
    public getSpoolSpoolSpoolIdGet(requestParameters: SpoolApiGetSpoolSpoolSpoolIdGetRequest, getSpoolSpoolSpoolIdGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SpoolDto>>;
    public getSpoolSpoolSpoolIdGet(requestParameters: SpoolApiGetSpoolSpoolSpoolIdGetRequest, getSpoolSpoolSpoolIdGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'spool_id': spoolId,
        } = requestParameters;

        if (spoolId === null || spoolId === undefined) {
            throw new Error('Required parameter spoolId was null or undefined when calling getSpoolSpoolSpoolIdGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<SpoolDto>(`${this.basePath}/spool/${encodeURIComponent(String(spoolId))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...getSpoolSpoolSpoolIdGetOpts?.config,
                        headers: {...headers, ...getSpoolSpoolSpoolIdGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Update Spool
     * Update any attribute of a spool. Only fields specified in the request will be affected. remaining_weight and used_weight can\&#39;t be set at the same time. If extra is set, all existing extra fields will be removed and replaced with the new ones.
     * @param {SpoolApiUpdateSpoolSpoolSpoolIdPatchRequest} requestParameters Request parameters.
     * @param {*} [updateSpoolSpoolSpoolIdPatchOpts.config] Override http request option.
     */
    public updateSpoolSpoolSpoolIdPatch(requestParameters: SpoolApiUpdateSpoolSpoolSpoolIdPatchRequest, updateSpoolSpoolSpoolIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SpoolDto>>;
    public updateSpoolSpoolSpoolIdPatch(requestParameters: SpoolApiUpdateSpoolSpoolSpoolIdPatchRequest, updateSpoolSpoolSpoolIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'spool_id': spoolId,
            'SpoolUpdateParametersDto': spoolUpdateParametersDto,
        } = requestParameters;

        if (spoolId === null || spoolId === undefined) {
            throw new Error('Required parameter spoolId was null or undefined when calling updateSpoolSpoolSpoolIdPatch.');
        }

        if (spoolUpdateParametersDto === null || spoolUpdateParametersDto === undefined) {
            throw new Error('Required parameter spoolUpdateParametersDto was null or undefined when calling updateSpoolSpoolSpoolIdPatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<SpoolDto>(`${this.basePath}/spool/${encodeURIComponent(String(spoolId))}`,
                    spoolUpdateParametersDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...updateSpoolSpoolSpoolIdPatchOpts?.config,
                        headers: {...headers, ...updateSpoolSpoolSpoolIdPatchOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Use Spool Filament Based On The Current Weight Measurement
     * Use some weight of filament from the spool. Specify the current gross weight of the spool.
     * @param {SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutRequest} requestParameters Request parameters.
     * @param {*} [useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutOpts.config] Override http request option.
     */
    public useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut(requestParameters: SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutRequest, useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SpoolDto>>;
    public useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut(requestParameters: SpoolApiUseSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutRequest, useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'spool_id': spoolId,
            'SpoolMeasureParametersDto': spoolMeasureParametersDto,
        } = requestParameters;

        if (spoolId === null || spoolId === undefined) {
            throw new Error('Required parameter spoolId was null or undefined when calling useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut.');
        }

        if (spoolMeasureParametersDto === null || spoolMeasureParametersDto === undefined) {
            throw new Error('Required parameter spoolMeasureParametersDto was null or undefined when calling useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePut.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<SpoolDto>(`${this.basePath}/spool/${encodeURIComponent(String(spoolId))}/measure`,
                    spoolMeasureParametersDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutOpts?.config,
                        headers: {...headers, ...useSpoolFilamentBasedOnTheCurrentWeightMeasurementSpoolSpoolIdMeasurePutOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Use Spool Filament
     * Use some length or weight of filament from the spool. Specify either a length or a weight, not both.
     * @param {SpoolApiUseSpoolFilamentSpoolSpoolIdUsePutRequest} requestParameters Request parameters.
     * @param {*} [useSpoolFilamentSpoolSpoolIdUsePutOpts.config] Override http request option.
     */
    public useSpoolFilamentSpoolSpoolIdUsePut(requestParameters: SpoolApiUseSpoolFilamentSpoolSpoolIdUsePutRequest, useSpoolFilamentSpoolSpoolIdUsePutOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SpoolDto>>;
    public useSpoolFilamentSpoolSpoolIdUsePut(requestParameters: SpoolApiUseSpoolFilamentSpoolSpoolIdUsePutRequest, useSpoolFilamentSpoolSpoolIdUsePutOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'spool_id': spoolId,
            'SpoolUseParametersDto': spoolUseParametersDto,
        } = requestParameters;

        if (spoolId === null || spoolId === undefined) {
            throw new Error('Required parameter spoolId was null or undefined when calling useSpoolFilamentSpoolSpoolIdUsePut.');
        }

        if (spoolUseParametersDto === null || spoolUseParametersDto === undefined) {
            throw new Error('Required parameter spoolUseParametersDto was null or undefined when calling useSpoolFilamentSpoolSpoolIdUsePut.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<SpoolDto>(`${this.basePath}/spool/${encodeURIComponent(String(spoolId))}/use`,
                    spoolUseParametersDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...useSpoolFilamentSpoolSpoolIdUsePutOpts?.config,
                        headers: {...headers, ...useSpoolFilamentSpoolSpoolIdUsePutOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
