/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PatternDto } from './pattern.dto';
import { SpoolmanExternaldbMultiColorDirectionDto } from './spoolmanExternaldbMultiColorDirection.dto';
import { FinishDto } from './finish.dto';
import { SpoolTypeDto } from './spoolType.dto';


export interface ExternalFilamentDto { 
    /**
     * A unique ID for this filament.
     */
    id: string;
    /**
     * Filament manufacturer.
     */
    manufacturer: string;
    /**
     * Filament name.
     */
    name: string;
    /**
     * Filament material.
     */
    material: string;
    /**
     * Density in g/cm3.
     */
    density: number;
    /**
     * Net weight of a single spool.
     */
    weight: number;
    'spool_weight'?: number | null;
    'spool_type'?: SpoolTypeDto | null;
    /**
     * Filament in mm.
     */
    diameter: number;
    'color_hex'?: string | null;
    'color_hexes'?: Array<string> | null;
    'extruder_temp'?: number | null;
    'bed_temp'?: number | null;
    finish?: FinishDto | null;
    'multi_color_direction'?: SpoolmanExternaldbMultiColorDirectionDto | null;
    pattern?: PatternDto | null;
    /**
     * Whether the filament is translucent.
     */
    translucent?: boolean;
    /**
     * Whether the filament is glow-in-the-dark.
     */
    glow?: boolean;
}
export namespace ExternalFilamentDto {
}


