/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ExtraFieldTypeDto = 'text' | 'integer' | 'integer_range' | 'float' | 'float_range' | 'datetime' | 'boolean' | 'choice';

export const ExtraFieldTypeDto = {
    Text: 'text' as ExtraFieldTypeDto,
    Integer: 'integer' as ExtraFieldTypeDto,
    IntegerRange: 'integer_range' as ExtraFieldTypeDto,
    Float: 'float' as ExtraFieldTypeDto,
    FloatRange: 'float_range' as ExtraFieldTypeDto,
    Datetime: 'datetime' as ExtraFieldTypeDto,
    Boolean: 'boolean' as ExtraFieldTypeDto,
    Choice: 'choice' as ExtraFieldTypeDto
};

