/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtraFieldTypeDto } from './extraFieldType.dto';
import { EntityTypeDto } from './entityType.dto';


export interface ExtraFieldDto { 
    /**
     * Nice name
     */
    name: string;
    /**
     * Order of the field
     */
    order?: number;
    unit?: string | null;
    /**
     * Type of the field
     */
    'field_type': ExtraFieldTypeDto;
    'default_value'?: string | null;
    choices?: Array<string> | null;
    'multi_choice'?: boolean | null;
    /**
     * Unique key
     */
    key: string;
    /**
     * Entity type this field is for
     */
    'entity_type': EntityTypeDto;
}
export namespace ExtraFieldDto {
}


