/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VendorDto } from './vendor.dto';
import { SpoolmanApiV1ModelsMultiColorDirectionDto } from './spoolmanApiV1ModelsMultiColorDirection.dto';


export interface FilamentDto { 
    /**
     * Unique internal ID of this filament type.
     */
    id: number;
    /**
     * When the filament was registered in the database. UTC Timezone.
     */
    registered: string;
    name?: string | null;
    vendor?: VendorDto | null;
    material?: string | null;
    price?: number | null;
    /**
     * The density of this filament in g/cm3.
     */
    density: number;
    /**
     * The diameter of this filament in mm.
     */
    diameter: number;
    weight?: number | null;
    'spool_weight'?: number | null;
    'article_number'?: string | null;
    comment?: string | null;
    'settings_extruder_temp'?: number | null;
    'settings_bed_temp'?: number | null;
    'color_hex'?: string | null;
    'multi_color_hexes'?: string | null;
    'multi_color_direction'?: SpoolmanApiV1ModelsMultiColorDirectionDto | null;
    'external_id'?: string | null;
    /**
     * Extra fields for this filament. All values are JSON-encoded data. Query the /fields endpoint for more details about the fields.
     */
    extra: { [key: string]: string; };
}
export namespace FilamentDto {
}


