/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SettingKVDto } from './settingKV.dto';
import { EventTypeDto } from './eventType.dto';


/**
 * Event.
 */
export interface SettingEventDto { 
    /**
     * Event type.
     */
    type: EventTypeDto;
    /**
     * Resource type.
     */
    resource: SettingEventDto.ResourceEnum;
    /**
     * When the event occured. UTC Timezone.
     */
    date: string;
    /**
     * Updated setting.
     */
    payload: SettingKVDto;
}
export namespace SettingEventDto {
    export type ResourceEnum = 'setting';
    export const ResourceEnum = {
        Setting: 'setting' as ResourceEnum
    };
}


