/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SettingTypeDto } from './settingType.dto';


export interface SettingResponseDto { 
    /**
     * Setting value.
     */
    value: string;
    /**
     * Whether the setting has been set. If false, \'value\' contains the default value.
     */
    'is_set': boolean;
    /**
     * Setting type. This corresponds with JSON types.
     */
    type: SettingTypeDto;
}
export namespace SettingResponseDto {
}


