/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of a setting.
 */
export type SettingTypeDto = 'boolean' | 'number' | 'string' | 'array' | 'object';

export const SettingTypeDto = {
    Boolean: 'boolean' as SettingTypeDto,
    Number: 'number' as SettingTypeDto,
    String: 'string' as SettingTypeDto,
    Array: 'array' as SettingTypeDto,
    Object: 'object' as SettingTypeDto
};

