/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpoolUpdateParametersDto { 
    'first_used'?: string | null;
    'last_used'?: string | null;
    'filament_id'?: number | null;
    price?: number | null;
    'initial_weight'?: number | null;
    'spool_weight'?: number | null;
    'remaining_weight'?: number | null;
    'used_weight'?: number | null;
    location?: string | null;
    'lot_nr'?: string | null;
    comment?: string | null;
    /**
     * Whether this spool is archived and should not be used anymore.
     */
    archived?: boolean;
    extra?: { [key: string]: string; } | null;
}

