/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilamentDto } from './filament.dto';


export interface SpoolDto { 
    /**
     * Unique internal ID of this spool of filament.
     */
    id: number;
    /**
     * When the spool was registered in the database. UTC Timezone.
     */
    registered: string;
    'first_used'?: string | null;
    'last_used'?: string | null;
    /**
     * The filament type of this spool.
     */
    filament: FilamentDto;
    price?: number | null;
    'remaining_weight'?: number | null;
    'initial_weight'?: number | null;
    'spool_weight'?: number | null;
    /**
     * Consumed weight of filament from the spool in grams.
     */
    'used_weight': number;
    'remaining_length'?: number | null;
    /**
     * Consumed length of filament from the spool in millimeters.
     */
    'used_length': number;
    location?: string | null;
    'lot_nr'?: string | null;
    comment?: string | null;
    /**
     * Whether this spool is archived and should not be used anymore.
     */
    archived: boolean;
    /**
     * Extra fields for this spool. All values are JSON-encoded data. Query the /fields endpoint for more details about the fields.
     */
    extra: { [key: string]: string; };
}

