/**
 * Spoolman REST API v1
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VendorDto { 
    /**
     * Unique internal ID of this vendor.
     */
    id: number;
    /**
     * When the vendor was registered in the database. UTC Timezone.
     */
    registered: string;
    /**
     * Vendor name.
     */
    name: string;
    comment?: string | null;
    'empty_spool_weight'?: number | null;
    'external_id'?: string | null;
    /**
     * Extra fields for this vendor. All values are JSON-encoded data. Query the /fields endpoint for more details about the fields.
     */
    extra: { [key: string]: string; };
}

